replicaCount: 1

image:
  repository: jimoh1990/payment-service
  pullPolicy: IfNotPresent
  tag: "v10"

service:
  type: NodePort       # Change from ClusterIP to NodePort
  port: 80
  nodePort: 30007
