{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "python-app.fullname" . }}-secrets
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: {{ .Values.secrets.storeName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "python-app.fullname" . }}-env
    creationPolicy: Owner
  data:
  {{- range $envName, $vaultConfig := .Values.secrets.vaultMappings }}
  - secretKey: {{ $envName }}
    remoteRef:
      key: {{ $vaultConfig.path }}
      property: {{ $vaultConfig.key }}
  {{- end }}
{{- end }}
