apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "python-app.fullname" . }}-quota
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
spec:
  hard:
    # The Namespace "Credit Limit"
    requests.cpu: "2"
    requests.memory: "2Gi"
    pods: "3"
    
    # Enforce that every pod MUST have limits defined
    count/resourcequotas: "1"

