{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "python-app.serviceAccountName" . }}
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
# SECURITY CRITICAL: 
# Prevent the app from talking to the K8s API (kubectl inside the pod)
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
{{- end }}
